# 池化层

## 实现池化层的正向传播

In [2]:
# 导包
import torch
from torch import nn
from d2l import torch as d2l

def pool2d(X, pool_size, mode = 'max'):
    p_h, p_w = pool_size            # p_h：池化窗口高；p_w：池化窗口宽
    Y =torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))        # 输出大小：(x_h - p_h + 1, x_w - p_w + 1)
    for i in range(Y.shape[0]):             # 行迭代
        for j in range(Y.shape[1]):         # 列迭代
            if mode == 'max':               # 最大池化
                Y[i, j] = X[i:i + p_h, j:j + p_w].max()         # 求窗口最大值
            elif mode == 'avg':             # 平均池化
                Y[i, j] = X[i:i + p_h, j:j + p_w].mean()        # 求窗口平均值
    return Y

## 验证二维最大池化层的输出

In [3]:
X = torch.tensor([[0., 1., 2.], [3., 4., 5.], [6., 7., 8.]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

## 验证平均池化层

In [4]:
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

## 填充和步幅

In [6]:
X = torch.arange(16, dtype = torch.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

## 深度学习框架中的步幅与池化窗口的大小相同

In [7]:
# 很多框架为了简化，若没有显式指定stride，就默认让步幅等于池化窗口大小，这样池化区域不重叠。
pool2d = nn.MaxPool2d(3)        # 这里的3指的是池化窗口的高和宽
pool2d(X)

tensor([[[[10.]]]])

## 填充和步幅可以手动设定

In [9]:
pool2d = nn.MaxPool2d(3, padding = 1, stride = 2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

## 设定一个任意大小的矩形池化窗口，并分别设定填充和步幅的高度和宽度

In [10]:
pool2d = nn.MaxPool2d((2, 3), padding = (1, 1), stride = (2, 3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

## 池化层在每个输入通道上单独运算

In [11]:
X = torch.cat((X, X + 1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [13]:
pool2d = nn.MaxPool2d(3, padding = 1, stride = 2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])