# 数据操作


首先，我们导入`torch`。请注意，虽然它被称为PyTorch，但我们应该导入`torch`而不是pytorch。

In [ ]:
import torch


张量表示一个数值组成的数组，这个数组可能有多个维度。

In [ ]:
x = torch.arange(12)
print(x)

我们可以通过张量的`shape`属性在访问张量的形状和张量中元素的总数

In [ ]:
x.shape     # 张量维度

In [ ]:
x.numel()   # number of elements 元素总数

要改变一个张量的形状而不改变元素数量和元素值，我们可以调用`reshape`函数。

In [ ]:
x = x.reshape(3, 4)     # 重塑成3行4列的矩阵
print(x)

使用全0、全1、其他常量或者从特定分布中随机采样的数字

In [ ]:
torch.zeros(2, 3, 4)

In [ ]:
torch.ones(2, 3, 4)

通过提供包含数值的Python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值

In [ ]:
torch.tensor([[2,1,4,3], [1,2,3,4], [4,3,2,1]]).shape

常见的标准算术运算符（`+`、`-`、`*`、`/`和`**`）都可以被升级为按元素运算

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y      # **运算符是求幂运算

按元素方式应用更多的计算

In [17]:
torch.exp(x)    # 指数运算

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

我们也可以把多个张量连结在一起

In [19]:
X = torch.arange(12, dtype= torch.float32).reshape((3,4))       # 生成一个0-11的，长度为12的，float32类型的，3行4列的张量
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim = 0), torch.cat((X, Y), dim = 1)      # dim = 0表示的是按行合并，dim = 1表示的是按列合并

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过逻辑运算符构建二元张量

In [20]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进行求和会产生一个只有一个元素的张量

In [21]:
X.sum()

tensor(66.)

即使形状不同，我们仍然可以通过调用*广播机制*（broadcasting mechanism）来执行按元素操作

In [23]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b    # a,b形状不同但维度一样都是2维

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
a + b   # 核心逻辑：将a和b复制成两个同样行列数的张量，这里的行列数取两个张量的最大值，如a为3行1列，b为1行2列，就将a和b均复制成3行2列的张量

可以用`[-1]`选择最后一个元素，可以用`[1:3]`选择第二个和第三个元素

In [26]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

除读取外，我们还可以通过指定索引来将元素写入矩阵

In [29]:
X[1, 2] = 9
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])


为多个元素赋值相同的值，我们只需要索引所有元素，然后为他们赋值

In [30]:
X[0:2, :] = 12  # 将0行与1行的所有列的值赋为12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

运行一些操作可能会导致为新结果分配内存

In [32]:
before = id(Y)      # id可以被认为是c++中指针般的存在
Y = Y + X
id(Y) == before     # 结果为before，说明内存地址已经发生改变

False

执行原地操作

In [33]:
Z = torch.zeros_like(Y)
print('id(z):', id(Z))
Z[ : ] = X + Y
print('id(z):', id(Z))      # 可以发现这里Z的内存地址未发生变化

id(z): 1880672892512
id(z): 1880672892512


如果在后续计算中没有重复使用`X`，我们也可以使用`X[ : ] = X + Y`或`X += Y`来减少操作的内存开销

In [34]:
before = id(X)
X += Y      # 或者是Z[ : ] = X + Y
id(X) == before

True

转换为NumPy张量

In [35]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为Python标量

In [36]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)