In [ ]:
# 导包
import numpy as np
import pandas as pd

# 1.Numpy属性介绍

## 1.1 创建ndarray对象

In [ ]:
# numpy -> 和数学操作相关的库，numpy的数组是多维的，并且是固定类型的，numpy的数组是ndarray，主要用于：矩阵运算

# 1.创建numpy的ndarray对象
arr1 = np.arange(15).reshape(3, 5)
print(arr1)        # 可以不用print语句也能输出，但如果下面还有输出内容，那么只会输出最后一个内容

## 1.2 演示numpy的常用属性

In [ ]:
print(f'numpy的轴：{arr1.ndim}')      # 2
print(f'numpy的维度：{arr1.shape}')     # (3, 5) 3行5列
print(f'numpy的元素类型：{arr1.dtype}')   # int64
print(f'numpy的元素个数：{arr1.size}')   # 15
print(f'numpy的元素占用字节数：{arr1.itemsize}')   # 8
print(f'numpy的元素类型：{type(arr1)}')   # <class 'numpy.ndarray'>

# 2.创建Numpy的ndarray对象

## 2.1 array()函数，把Python列表 -> ndarray对象

In [ ]:
# 1.创建python列表对象
my_list = [11, 22, 33, 44, 55]
print(type(my_list))    #<class 'list'>

# 2.把python列表 -> ndarray对象
arr2 = np.array(my_list)
print(arr2)     # [11,22,33,44,55]
print(type(arr2))   # <class 'numpy.ndarray'>

## 2.2 arange()函数，创建ndarray对象

In [ ]:
# arange(起始, 结束, 步长, dtype = 类型)，类似于Python中的range()函数，
# 1.创建ndarray对象
arr3 = np.arange(0, 10, 2, dtype = np.int64)      # 不包含结束位置的数（包左不包右）
# 2.打印ndarray对象
print(arr3)
print(type(arr3))
print(f'元素的类型：{arr3.dtype}')

## 2.3 随机数生成ndarray对象

In [ ]:
# 1.random.rand() 生成0.0-1.0之间，包左不包右的随机小数矩阵
arr4 = np.random.rand(3, 5)     # 3行5列
print(arr4)
print(type(arr4))

In [ ]:
# 2.random.randint(起始值, 结束值, size= (行, 列)) 生成指定范围，包左不包右的随机整数矩阵
arr5 = np.random.randint(3, 9, size= (2, 6))     # 3-9之间，包左不包右，2行6列
print(arr5)
print(type(arr5))

In [ ]:
# 3.random.uniform(起始值, 结束值, size= (行, 列)) 生成指定范围，包左不包右的随机小数矩阵
arr6 = np.random.uniform(3, 9, size= (2, 6))     # 3-9之间，包左不包右，2行6列
print(arr6)
print(type(arr6))

## （Day17）2.4 numpy的类型转换 -> astype()

In [ ]:
# 1.创建ndarray对象
arr7 = np.arange(0, 10, 2, dtype = np.int64)      # 不包含结束位置的数（包左不包右）
print(arr7)
print(arr7.dtype)

In [ ]:
# 2.把上述的arr7 ndarray对象的元素从int64 -> float32
arr8 = arr7.astype(np.float32)
print(arr8)
print(arr8.dtype)


## 2.5 创建等比数列

In [ ]:
# 1.创建等比数列 ---> 参1：起始值(充当10的指数)，参2：结束值(充当10的指数)，参3：元素个数
arr9 = np.logspace(0, 3, 4)     # 注：起始点为10^0 = 1,终止点为10^3 = 1000
# 2.打印ndarray对象
print(arr9)
print(arr9.dtype)

In [ ]:
# 3.创建等比数列 ---> 参1：起始值(充当2的指数)，参2：结束值(充当2的指数)，参3：元素个数，参4：修改底数（指数）为2，参5：修改数据类型为int64
arr9 = np.logspace(0, 3, 4, base = 2, dtype = np.int64)     # 注：起始点为10^0 = 1,终止点为10^3 = 1000
# 4.打印ndarray对象
print(arr9)
print(arr9.dtype)

## 2.6 创建等差数列

In [ ]:
# 1.创建等差数列 ---> 参1：起始值，参2：结束值，参3：元素个数，参4：是否包含终止值，参5：修改数据类型为int64
arr10 = np.linspace(1, 10, 4,endpoint = False, dtype = np.int64)
# 2.打印ndarray对象
print(arr10)
print(arr10.dtype)

# 3.演示Numpy常用函数

## 3.1 基本函数

In [25]:
# 1.创建标准的正态分布的序列
arr1 = np.random.randn(3, 5)    # 创建3行5列标准正态分布的序列
print(arr1)

[[-0.44177615  0.82533283 -0.24943791 -1.08085378 -0.30314861]
 [-1.20372584  0.44826723 -0.99129082  0.08042066  1.25682982]
 [ 1.00283473 -0.19262881  1.21978052  0.87587134  0.02427256]]


In [36]:
# 2.测试基本函数
# print(np.ceil(arr1))    # 向上取整
# print(np.floor(arr1))    # 向下取整
# print(np.rint(arr1))    # 四舍五入
# print(np.abs(arr1))    # 取绝对值

# print(np.multiply(arr1, arr1))    # 矩阵乘法（行列数一致）
# print(arr1 * arr1)      # 结果与multiply方法一致

# print(np.divide(arr1, arr1))     # 矩阵除法（行列数一致）
print(np.where(arr1 > 0, 1, -1))    # 类似于Python中的三元表达式，意为1 if arr1 >0 else -1

[[-1  1 -1 -1 -1]
 [-1  1 -1  1  1]
 [ 1 -1  1  1  1]]


# 4.Numpy的矩阵运算

## 4.1 加减法运算

In [37]:
# 1.定义数组
arr1 = np.array([10, 20, 30, 40])
arr2 = np.arange(4)

# 2.打印数组
print("arr1：", arr1)
print("arr2：", arr2)

arr1： [10 20 30 40]
arr2： [0 1 2 3]


In [38]:
# 3.减法运算
print(arr1 - arr2)      # 对应位置元素做减法

[10 19 28 37]


In [41]:
# 4.加法运算
print(arr1 + arr2)      # 对应位置元素做加法

[10 21 32 43]


## 4.2 矩阵乘法

In [43]:
# 1.定义数组
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# 2.打印数组
print("arr1：", arr1)
print("arr2：", arr2)

arr1： [[1 2 3]
 [4 5 6]]
arr2： [[1 2 3]
 [4 5 6]]


In [45]:
# 3.矩阵乘法（行列数一致） -> 对应位置元素相乘
print(arr1 * arr2)      # 对应位置元素相乘
# print(np.multiply(arr1, arr2))      # 效果同上

[[ 1  4  9]
 [16 25 36]]


In [46]:
# 4.矩阵乘法（行列数不一致） -> 参照线性代数方法
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[9, 8], [6, 5], [3, 2]])
# 5.打印数组
print("arr3：", arr3)
print("arr4：", arr4)

arr3： [[1 2 3]
 [4 5 6]]
arr4： [[9 8]
 [6 5]
 [3 2]]


In [50]:
# 6.矩阵乘法（行列数不一致） -> 参照线性代数方法
# print(arr3 * arr4)      # 报错，行列数不一致

print(arr3 @ arr4)      # 语法糖，A：2行3列，B：3行2列，A列 = B行即可操作，结果是：A行B列数组
print(np.dot(arr3, arr4))      # np.dot()函数适用于行列数不一致时的矩阵乘法
print(arr3.dot(arr4))      # 效果同上

[[30 24]
 [84 69]]
[[30 24]
 [84 69]]
[[30 24]
 [84 69]]


In [54]:
# 7.验证：A列 = B行即可操作，结果是：A行B列数组
arr3 = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])   # 2行4列
arr4 = np.array([[9, 8], [6, 5], [3, 2]])   # 3行2列
print(arr3 @ arr4)      # 不符合A列 = B行

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)