# 线性代数

标量由只有一个元素的张量表示

In [107]:
import torch

x= torch.tensor([3.0])
y= torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

你可以将向量视为标量值组成的列表

In [108]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

通过张量的索引来访问任一元素

In [109]:
x[3]

tensor(3)

访问张量的长度

In [110]:
len(x)

4

只有一个轴的张量，形状只有一个元素。

In [111]:
x.shape

torch.Size([4])

通过指定两个分量*m*和*n*来创建一个形状为*m×n*的矩阵

In [112]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置

In [113]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵（symmetric matrix）A等于其转置：A = Aᵀ

In [114]:
B = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [115]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构

In [116]:
X = torch.arange(24).reshape(2, 3, 4)   # 参3为列数，参2为行数，参1为维度数
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [117]:
A = torch.arange(20, dtype = torch.float32).reshape(5, 4)
B = A.clone()   # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵的按元素乘法成为*哈达玛积*（Hadamard product）（数学符号⊙）

In [118]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [119]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape    # 张量与标量相加，即将张量中的每个元素加上标量的数值

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

计算其元素的和

In [120]:
x = torch.arange(4, dtype = torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

表示任意形状张量的元素和

In [121]:
A = torch.arange(20 * 2).reshape(5, 4)
A.shape, A.sum()

RuntimeError: shape '[5, 4]' is invalid for input of size 40

指定求和汇总张量的轴

In [ ]:
print(A)
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

In [ ]:
print(A)
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

In [ ]:
A.sum(axis = [0, 1]).shape      # 与A.sum()相同

In [ ]:
print(A)
A_sum_axis2 = A.sum(axis=2)
A_sum_axis2, A_sum_axis2.shape

一个与求和相关的量是*平均值*（mean或average）

In [ ]:
A.mean(dtype=torch.float32), A.sum() / A.numel()

In [ ]:
A.mean(axis = 0,dtype=torch.float32), A.sum(axis = 0) / A.shape[0]

计算总和或均值时保持轴数不变

In [139]:
sum_A = A.sum(axis=1,keepdim=True)      # 这样仍然保持输出的矩阵为3维
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

通过广播将`A`除以`sum_A`

In [140]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

某个轴计算`A`元素的累计总和

In [ ]:
A.cumsum(axis = 0)

点积是相同位置的按元素乘积的和

In [ ]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积

In [ ]:
torch.sum(x * y)

矩阵向量积Ax是一个长度为m的列向量，其iᵗʰ元素是点积aᵀix

In [122]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

我们可以将矩阵-矩阵乘法AB看作是简单地执行m次矩阵-向量积，并将结果拼接在一起，形成一个n×m矩阵

In [126]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L2范数是向量元素平方和的平方根

In [127]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)   # norm = (3^^2 + 4^^2)开根号

tensor(5.)

L1范数表示为向量元素的绝对值之和

In [128]:
torch.abs(u).sum()

tensor(7.)

矩阵的*弗罗贝尼乌斯范数*（Frobenius norm）是矩阵元素的平方和的平方根

In [129]:
torch.norm(torch.ones(4, 9))        # 即4*9个1相加等于36，然后开平方等于6

tensor(6.)

按特定轴求和补充

In [130]:
a = torch.ones((2,5,4))
a.shape

torch.Size([2, 5, 4])

In [136]:
a.sum(axis=[0,2]).shape     # 这里的[0,2]表示第0维和第2维

torch.Size([5])

In [138]:
a.sum(axis=[0,2], keepdim=True).shape   # 这里的[0,2]表示第0维和第2维

torch.Size([1, 5, 1])