# 自动求导

假设我们想对函数 y = 2xᵀx 关于列向量x求导

In [ ]:
import torch

x = torch.arange(4.0)
x

在我们计算y关于x的梯度之前，我们需要一个地方来存储梯度。

In [ ]:
x.requires_grad_(True)   # 等价于x = torch.arange(4.0, requires_grad = True)
x.grad      # 用于访问梯度，默认值是None

现在让我们计算y

In [ ]:
y = 2 * torch.dot(x, x)
y

通过调用反向传播函数来自动计算`y`关于`x`每个分量的梯度

In [ ]:
y.backward()    # 求导函数
x.grad

In [ ]:
x.grad == 4 * x

现在让我们计算x的另一个函数

In [26]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()      # 清除之前的值（PyTorch中结尾有下划线的函数意为重写内容）
y = x.sum()     # 新函数
y.backward()
x.grad

tensor([1., 1., 1., 1.])

深度学习中，我们的目的不是计算微分矩阵，而是批量中每个样本单独计算的偏导数之和

In [28]:
# 对非标量调用backward需要传入一个gradient参数，该参数指定微分函数
x.grad.zero_()
y = x * x
y.sum().backward()      # 等价于y.backward(torch.ones(len(x)))
x.grad

tensor([0., 2., 4., 6.])

将某些计算移动到记录的计算图之外

In [29]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [30]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])